In [ ]:
# Simple Ola Project : -

In [1]:
import pandas as pd

In [2]:
#step 1: Create the DataFrames
data={
    'Ride_ID':['R001','R002','R003','R004','R005','R006','R007','R008','R009','R010','R010'],
    
    'Customer_Name':['Amit','Rahul','Rupali','Sanika','Snehal','Poonam','Sanjana','Anish','Avanti','Ankita','Ankita'],

    'Driver_Name':['Raj','Akash','Suresh','Vijay','Rohit','Akshay','Prakash','Sameer','Nitin','Ganesh','Ganesh'],
    
    'City':['Satara','Pune','Mumbai','Nashik','Mumbai','Pune','Sangli','Satara','Kolhapure','Pune','Pune'],
    
    'Ride_Type':['Mini','Prime','Auto','Mini','Prime','Auto','Mini','Prime','Auto','Mini','Mini'],
    
    'Distance_KM':[12,18,7,15,20,5,10,25,8,14,14],
    
    'Fare':[250,500,120,300,650,100,220,700,150,280,280],
    
    'Payment_Mode':['UPI','UPI','Cash','Card','Cash','UPI','Cash','Card','UPI',None,None],
    
    'Rating':[4.5,4.8,4.0,4.2,4.9,3.8,4.5,5.0,4.1,None,None],
    
    'Ride_Status':['Completed','Completed','Cancelled','Completed','Completed','Completed','Cancelled',None,'Cancelled','Completed','Completed']
    
}
df=pd.DataFrame(data)
df

,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
2,R003,Rupali,Suresh,Mumbai,Auto,7,120,Cash,4.0,Cancelled
3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
5,R006,Poonam,Akshay,Pune,Auto,5,100,UPI,3.8,Completed
6,R007,Sanjana,Prakash,Sangli,Mini,10,220,Cash,4.5,Cancelled
7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN
8,R009,Avanti,Nitin,Kolhapure,Auto,8,150,UPI,4.1,Cancelled
9,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,NaN,Completed
10,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,NaN,Completed

In [3]:
# STEP 2:store data
df.to_csv('Ola project.csv')

In [4]:
# STEP 3:read data
df=pd.read_csv('Ola project.csv')

In [5]:
# STEP 4 :Understand data
df.head()

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
2,2,R003,Rupali,Suresh,Mumbai,Auto,7,120,Cash,4.0,Cancelled
3,3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed

In [6]:
df.tail()

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
6,6,R007,Sanjana,Prakash,Sangli,Mini,10,220,Cash,4.5,Cancelled
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN
8,8,R009,Avanti,Nitin,Kolhapure,Auto,8,150,UPI,4.1,Cancelled
9,9,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,NaN,Completed
10,10,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,NaN,Completed

In [7]:
df.head(7)

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
2,2,R003,Rupali,Suresh,Mumbai,Auto,7,120,Cash,4.0,Cancelled
3,3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
5,5,R006,Poonam,Akshay,Pune,Auto,5,100,UPI,3.8,Completed
6,6,R007,Sanjana,Prakash,Sangli,Mini,10,220,Cash,4.5,Cancelled

In [8]:
df.tail(4)

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN
8,8,R009,Avanti,Nitin,Kolhapure,Auto,8,150,UPI,4.1,Cancelled
9,9,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,NaN,Completed
10,10,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,NaN,Completed

In [9]:
df.shape

(11, 11)

In [10]:
df.columns #display columns in the table

Index(['Unnamed: 0', 'Ride_ID', 'Customer_Name', 'Driver_Name', 'City',
       'Ride_Type', 'Distance_KM', 'Fare', 'Payment_Mode', 'Rating',
       'Ride_Status'],
      dtype='str')

In [11]:
df.describe()

       Unnamed: 0  Distance_KM        Fare    Rating
count   11.000000    11.000000   11.000000  9.000000
mean     5.000000    13.454545  322.727273  4.422222
std      3.316625     5.972665  205.284725  0.423609
min      0.000000     5.000000  100.000000  3.800000
25%      2.500000     9.000000  185.000000  4.100000
50%      5.000000    14.000000  280.000000  4.500000
75%      7.500000    16.500000  400.000000  4.800000
max     10.000000    25.000000  700.000000  5.000000

In [12]:
df.describe

<bound method NDFrame.describe of     Unnamed: 0 Ride_ID Customer_Name Driver_Name       City Ride_Type  \
0            0    R001          Amit         Raj     Satara      Mini
1            1    R002         Rahul       Akash       Pune     Prime
2            2    R003        Rupali      Suresh     Mumbai      Auto
3            3    R004        Sanika       Vijay     Nashik      Mini
4            4    R005        Snehal       Rohit     Mumbai     Prime
5            5    R006        Poonam      Akshay       Pune      Auto
6            6    R007       Sanjana     Prakash     Sangli      Mini
7            7    R008         Anish      Sameer     Satara     Prime
8            8    R009        Avanti       Nitin  Kolhapure      Auto
9            9    R010        Ankita      Ganesh       Pune      Mini
10          10    R010        Ankita      Ganesh       Pune      Mini

    Distance_KM  Fare Payment_Mode  Rating Ride_Status
0            12   250          UPI     4.5   Completed
1            18   500          UPI     4.8   Completed
2             7   120         Cash     4.0   Cancelled
3            15   300         Card     4.2   Completed
4            20   650         Cash     4.9   Completed
5             5   100          UPI     3.8   Completed
6            10   220         Cash     4.5   Cancelled
7            25   700         Card     5.0         NaN
8             8   150          UPI     4.1   Cancelled
9            14   280          NaN     NaN   Completed
10           14   280          NaN     NaN   Completed  >

In [13]:
# STEP 5:Data Cleaning
df.isnull()

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,True,True,False
10,False,False,False,False,False,False,False,False,True,True,False

In [15]:
df.isnull().sum()

Unnamed: 0       0
Ride_ID          0
Customer_Name    0
Driver_Name      0
City             0
Ride_Type        0
Distance_KM      0
Fare             0
Payment_Mode     2
Rating           2
Ride_Status      1
dtype: int64

In [16]:
df = df.drop_duplicates()
df

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
2,2,R003,Rupali,Suresh,Mumbai,Auto,7,120,Cash,4.0,Cancelled
3,3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
5,5,R006,Poonam,Akshay,Pune,Auto,5,100,UPI,3.8,Completed
6,6,R007,Sanjana,Prakash,Sangli,Mini,10,220,Cash,4.5,Cancelled
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN
8,8,R009,Avanti,Nitin,Kolhapure,Auto,8,150,UPI,4.1,Cancelled
9,9,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,NaN,Completed
10,10,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,NaN,Completed

In [17]:
df=df[df['Customer_Name']!='Ankita']
df

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
2,2,R003,Rupali,Suresh,Mumbai,Auto,7,120,Cash,4.0,Cancelled
3,3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
5,5,R006,Poonam,Akshay,Pune,Auto,5,100,UPI,3.8,Completed
6,6,R007,Sanjana,Prakash,Sangli,Mini,10,220,Cash,4.5,Cancelled
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN
8,8,R009,Avanti,Nitin,Kolhapure,Auto,8,150,UPI,4.1,Cancelled

In [18]:
#STEP 6 : handle missing values
df['Rating']=df['Rating'].fillna(df['Rating'].mean())
df

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
2,2,R003,Rupali,Suresh,Mumbai,Auto,7,120,Cash,4.0,Cancelled
3,3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
5,5,R006,Poonam,Akshay,Pune,Auto,5,100,UPI,3.8,Completed
6,6,R007,Sanjana,Prakash,Sangli,Mini,10,220,Cash,4.5,Cancelled
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN
8,8,R009,Avanti,Nitin,Kolhapure,Auto,8,150,UPI,4.1,Cancelled

In [89]:
df.fillna(5)

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
2,2,R003,Rupali,Suresh,Mumbai,Auto,7,120,Cash,4.0,Cancelled
3,3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
5,5,R006,Poonam,Akshay,Pune,Auto,5,100,UPI,3.8,Completed
6,6,R007,Sanjana,Prakash,Sangli,Mini,10,220,Cash,4.5,Cancelled
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,5
8,8,R009,Avanti,Nitin,Kolhapure,Auto,8,150,UPI,4.1,Cancelled

In [90]:
# STEP 7: EXAMPLES:-
#how many rides are there ?
df['Ride_ID'].count()

np.int64(9)

In [91]:
#Final total revenue ?
df['Fare'].sum()

np.int64(2990)

In [92]:
#Find average fare ?
df['Fare'].mean()

np.float64(332.22222222222223)

In [93]:
#Find Maximum fare ?
df['Fare'].max()

np.int64(700)

In [95]:
#Find Minimum fare ?
df['Fare'].min()

np.int64(100)

In [96]:
#Group by Analysis
#Revenue by city ?
df.groupby('City')['Fare'].sum()

City
Kolhapure    150
Mumbai       770
Nashik       300
Pune         600
Sangli       220
Satara       950
Name: Fare, dtype: int64

In [97]:
#Number of Rides by ride type ?
df.groupby('Ride_Type')['Ride_ID'].count()

Ride_Type
Auto     3
Mini     3
Prime    3
Name: Ride_ID, dtype: int64

In [98]:
#Average Rating by ride type ?
df.groupby('Ride_Type')['Rating'].mean()

Ride_Type
Auto     3.966667
Mini     4.400000
Prime    4.900000
Name: Rating, dtype: float64

In [100]:
#Revenue by payment mode ?
df.groupby('Payment_Mode')['Fare'].sum()

Payment_Mode
Card    1000
Cash     990
UPI     1000
Name: Fare, dtype: int64

In [101]:
#filtering
#find ride above 500 ?
df[df['Fare'] > 500]

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN

In [102]:
#find completed rides ? 
df[df['Ride_Status']=="Completed"]

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
3,3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
5,5,R006,Poonam,Akshay,Pune,Auto,5,100,UPI,3.8,Completed

In [88]:
#find pune rides ?
df[df["City"]=="Pune"]

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.800000,Completed
5,5,R006,Poonam,Akshay,Pune,Auto,5,100,UPI,3.800000,Completed
9,9,R010,Ankita,Ganesh,Pune,Mini,14,280,NaN,4.422222,Completed

In [103]:
#find the rides with rating above 4.5 ?
df[df['Rating']>4.5]

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN

In [104]:
#top 5 highest-fare rides ?
df.sort_values('Fare',ascending=False).head(5)

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
3,3,R004,Sanika,Vijay,Nashik,Mini,15,300,Card,4.2,Completed
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed

In [92]:
#top 3 drivers by total revenue ?
df.groupby('Driver_Name')['Fare'].sum().sort_values(ascending=False).head(3)

Driver_Name
Sameer    700
Rohit     650
Akash     500
Name: Fare, dtype: int64

In [106]:
#Find the average distance by city ?
df.groupby('City')['Distance_KM'].mean()

City
Kolhapure     8.0
Mumbai       13.5
Nashik       15.0
Pune         11.5
Sangli       10.0
Satara       18.5
Name: Distance_KM, dtype: float64

In [108]:
#find the most-used payment mode ?
df['Payment_Mode'].value_counts().head(1)

Payment_Mode
UPI    4
Name: count, dtype: int64

In [109]:
#find the most popular ride type ?
df['Ride_Type'].value_counts().head(1)

Ride_Type
Mini    3
Name: count, dtype: int64

In [110]:
#find total number of completed rides ?
df[df["Ride_Status"] == "Completed"].shape[0]

5

In [111]:
#find total revenue from completed rides ?
total=df[df["Ride_Status"]=="Completed"]['Fare'].sum()
total

np.int64(1800)

In [112]:
#find the average fare for each city ?
df.groupby('City')['Fare'].mean()

City
Kolhapure    150.0
Mumbai       385.0
Nashik       300.0
Pune         300.0
Sangli       220.0
Satara       475.0
Name: Fare, dtype: float64

In [113]:
#find the city with highest revenue ?
df.groupby('City')['Fare'].sum().sort_values(ascending=False)

City
Satara       950
Mumbai       770
Pune         600
Nashik       300
Sangli       220
Kolhapure    150
Name: Fare, dtype: int64

In [113]:
#find the ride type with the highest average fare ?
avg_fare = df.groupby('Ride_Type')['Fare'].mean()
avg_fare

Ride_Type
Auto     123.333333
Mini     262.500000
Prime    616.666667
Name: Fare, dtype: float64

In [114]:
#find the top 5 highest rated drivers ?
df.sort_values('Rating',ascending=False).head(5)

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
1,1,R002,Rahul,Akash,Pune,Prime,18,500,UPI,4.8,Completed
0,0,R001,Amit,Raj,Satara,Mini,12,250,UPI,4.5,Completed
6,6,R007,Sanjana,Prakash,Sangli,Mini,10,220,Cash,4.5,Cancelled

In [115]:
#find the top 3 cities based on total revenue ?
df.groupby('City')['Fare'].sum().sort_values(ascending=False).head(3)

City
Satara    950
Mumbai    770
Pune      600
Name: Fare, dtype: int64

In [123]:
#find rides where fare > 500 and rating >4 ? 
df[(df['Fare'] > 500) & (df['Rating'] > 4)]

,Unnamed: 0,Ride_ID,Customer_Name,Driver_Name,City,Ride_Type,Distance_KM,Fare,Payment_Mode,Rating,Ride_Status
4,4,R005,Snehal,Rohit,Mumbai,Prime,20,650,Cash,4.9,Completed
7,7,R008,Anish,Sameer,Satara,Prime,25,700,Card,5.0,NaN

In [116]:
#find the percentage of completed vs cancelled Rides ?
df['Ride_Status'].value_counts()

Ride_Status
Completed    5
Cancelled    3
Name: count, dtype: int64

In [117]:
df['Ride_Status'].value_counts(normalize=True) * 100

Ride_Status
Completed    62.5
Cancelled    37.5
Name: proportion, dtype: float64